name: voice_message_package_2
description: Flutter package to play/puase voice message in chat messengers.
version: 1.0.31
homepage: https://github.com/mehranshoqi/voice_message_player

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  just_audio: ^0.10.3
  audioplayers: ^6.4.0
  syncfusion_flutter_sliders: ^29.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


